version: "3.8"

services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    depends_on:
      - mongo
    networks:
      - internal
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.50"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file: .env
    depends_on:
      - mongo
    networks:
      - internal
    ports:
      - "${ADMIN_UI_PORT}:${ADMIN_UI_PORT}"
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.25"

  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_DATABASE: botdb
    networks:
      - internal

volumes:
  db:

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
    driver_opts:
      com.docker.network.bridge.name: br-dnsfix